// User seed data with plain text passwords to be hashed at runtime
const usersSeed = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    password: 'Password123!',
    phone: '+1234567890',
    address: '123 Main St',
    city: 'Dhaka',
    post_code: '1000',
    country: 'Bangladesh',
    region: 'Dhaka Division',
    role: 'customer'
  },
  {
    id: 2,
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    password: 'Password123!',
    phone: '+1987654321',
    address: '456 Oak Ave',
    city: 'Chittagong',
    post_code: '4000',
    country: 'Bangladesh',
    region: 'Chittagong Division',
    role: 'customer'
  },
  {
    id: 3,
    first_name: 'Admin',
    last_name: 'User',
    email: 'admin@example.com',
    password: 'Admin123!',
    phone: '+1122334455',
    address: '789 Admin St',
    city: 'Dhaka',
    post_code: '1000',
    country: 'Bangladesh',
    region: 'Dhaka Division',
    role: 'admin'
  },
  {
    id: 4,
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.j@example.com',
    password: 'Password123!',
    phone: '+1555666777',
    address: '101 Pine Rd',
    city: 'Khulna',
    post_code: '9000',
    country: 'Bangladesh',
    region: 'Khulna Division',
    role: 'customer'
  },
  {
    id: 5,
    first_name: 'Michael',
    last_name: 'Brown',
    email: 'michael.b@example.com',
    password: 'Password123!',
    phone: '+1777888999',
    address: '202 Maple Dr',
    city: 'Rajshahi',
    post_code: '6000',
    country: 'Bangladesh',
    region: 'Rajshahi Division',
    role: 'customer'
  },
  {
    id: 6,
    first_name: 'Emily',
    last_name: 'Davis',
    email: 'emily.d@example.com',
    password: 'Password123!',
    phone: '+1333444555',
    address: '303 Cedar Ln',
    city: 'Sylhet',
    post_code: '3100',
    country: 'Bangladesh',
    region: 'Sylhet Division',
    role: 'customer'
  },
  {
    id: 7,
    first_name: 'David',
    last_name: 'Wilson',
    email: 'david.w@example.com',
    password: 'Password123!',
    phone: '+1222333444',
    address: '404 Birch Blvd',
    city: 'Dhaka',
    post_code: '1000',
    country: 'Bangladesh',
    region: 'Dhaka Division',
    role: 'customer'
  },
  {
    id: 8,
    first_name: 'Support',
    last_name: 'Admin',
    email: 'support@example.com',
    password: 'Support123!',
    phone: '+1999888777',
    address: '505 Support Ave',
    city: 'Dhaka',
    post_code: '1000',
    country: 'Bangladesh',
    region: 'Dhaka Division',
    role: 'admin'
  },
  {
    id: 8,
    first_name: 'AB',
    last_name: 'CD',
    email: 'abcd49800@gmail.com',
    password: 'Password123!',
    phone: '+8801827829617',
    address: '505 Support Ave',
    city: 'Dhaka',
    post_code: '1000',
    country: 'Bangladesh',
    region: 'Dhaka Division',
    role: 'customer'
  }
];

export default usersSeed;
